### ISSUE TITLE
How to set the similar desktop minimize icon

### ISSUE THREAD

**Issue by mei2015** [fyne-io/developer.fyne.io#82] opened 2022-06-01 03:03 UTC
![image](https://user-images.githubusercontent.com/10136065/171319382-2e31da4c-6338-47dd-8115-9ce12fc1db1d.png)
How to set the similar desktop minimize icon

**Comment by Jacalz** [comment] 2022-06-01 05:44
Could you please elaborate on what you mean? I’m not quite sure I understand the question.

Also, I think this is the wrong repository given that this is the developer documentation website. I think you meant to use https://github.com/fyne-io/fyne.

**Comment by andydotxyz** [comment] 2022-06-01 20:37
I think they are asking for the system tray support that will be available in the release coming in the next days.
Closing as duplicate of the fyne ticket opened

**Closed by andydotxyz** 2022-06-01 20:37 UTC
