### ISSUE TITLE
table.ScrollToBottom causes crash/panic

### ISSUE THREAD

**Issue by dimitrove** [fyne-io/developer.fyne.io#76] opened 2022-04-13 15:32 UTC
The attached test:
-works after "go run . 12" and click
-crashes after "go run . 4" and click
[main.txt](https://github.com/fyne-io/developer.fyne.io/files/8482714/main.txt)

**Comment by Jacalz** [comment] 2022-04-13 16:49
As I wrote on your last issue, this is the wrong bug tracker for issues about Fyne. This one is only for things related to the developer website. I’ll close this  as a duplicate of the other issue that I transferred to the right place: https://github.com/fyne-io/fyne/issues/2918.

**Closed by Jacalz** 2022-04-13 16:49 UTC

**Comment by dimitrove** [comment] 2022-04-14 09:25
I apologize. I did not see your email about issue#75. I did not find
issue#75 among all issues at

https://github.com/fyne-io/developer.fyne.io/issues

(because - I understand now - it was transferred).
I got upset. I am sorry.

**Comment by Jacalz** [comment] 2022-04-14 10:30
No worries. We all make mistakes.
