### ISSUE TITLE
'NSUserNotification' is deprecated?

### ISSUE THREAD

**Issue by Atomzwieback** [fyne-io/developer.fyne.io#39] opened 2021-05-29 17:50 UTC
`warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
`

Tried out this lib today but it seems like there is a deprecated warning for the macos dependencys?

**Comment by Jacalz** [comment] 2021-05-29 20:27
It is just a warning not an error. It will work just fine until we can fix the deprecation notice. We can not do so as of yet because it would break older macOS versions.

This is a duplicate of https://github.com/fyne-io/fyne/issues/1833, though please be aware that you opened the issue in the wrong repository. This is just for the code of the website, not the project itself. The project is hosted at https://github.com/fyne-io/fyne.

**Comment by andydotxyz** [comment] 2021-05-30 20:01
Thanks for pointing out the duplicate @Jacalz

**Closed by andydotxyz** 2021-05-30 20:01 UTC
